version = "3.9.8"

runner.dialect = scala213

maxColumn = 120

align.preset = most

danglingParentheses.preset = true

newlines.topLevelStatements = [before]

continuationIndent.defnSite = 2
continuationIndent.callSite = 2

docstrings.style = Asterisk